# Site settings
title: MaiaDB
email: manismistry@live.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Web-designer, programmer, animator.
baseurl: "/MaiaDB/" # the subpath of your site, e.g. /blog/
url: "https://maiadb.com" # the base hostname & protocol for your site
enforce_ssl: www.maiadb.com
twitter_username: NetSlayerUK
github_username:  Net-Slayer
exclude: [
.git,
.gitignore,
.DS_Store,
CNAME,
svg,
scss,
pre_sass,
compat,
.sass-cache,
package.json,
Gruntfile.js,
node_modules,
readme.md,
templates,
Source,
htmtmp,
js/global,
js/total,
js/libs,
images/global,
release/css/global,
release/css/total,
gemfile,
Gemfile.lock,
.src.html,
.min.html,
.rep.html,
]

# Build settings
markdown: kramdown
